# Retrieve the last positions "latlong" by organization and limiting by timestamp 

query getLatestLatLong($org: String, $lastTS: Timestamp) {
  telemetry_latest(
    options: { pageSize: 100 }
    filter: {
      organization_id: { eq: $org }
      key: { eq: "latlong" }
      ts: { gt: $lastTS }
    }
  ) {
    values {
      lat: value
      long: value2
      device_id
      ts
    }
  }
}
